apiVersion: v1
kind: Service
metadata:
  name: pedido-micro-parcial
  labels:
    app: pedido-micro-parcial
spec:
  type: LoadBalancer  
  selector:
    app: pedido-micro-parcial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080