apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-micro-parcial 
  labels:
    app: pedido-micro-parcial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedido-micro-parcial
  template:
    metadata:
      labels:
        app: pedido-micro-parcial
    spec:
      containers:
      - name: pedido-micro-parcial
        image: aflorezg/parcial-arquitectura:1d30c90c493a6a452a3098a90eb7af7ec4ef04e7
        ports:
        - containerPort: 8080
        startupProbe:
            httpGet:
                path: /api/pedido/generar-pedido
                port: 8080
            initialDelaySeconds: 25
            
